enum envEnum {
  LOG_FILE = 'LOG_FILE',
  WARN_FILE = 'WARN_FILE',
  ERR_FILE = 'ERR_FILE',
  LOG_LINE_SPLITTER = 'LOG_LINE_SPLITTER',

  PROVIDER = 'PROVIDER',
  PROVIDER_OWNER = 'PROVIDER_OWNER',
  PROVIDER_TOKEN = 'PROVIDER_TOKEN',
  PROVIDER_REPO = 'PROVIDER_REPO',
  PROVIDER_PR_NUMBER = 'PROVIDER_PR_NUMBER',
  PROVIDER_API_URL = 'PROVIDER_API_URL',
  PROVIDER_REPO_URL = 'PROVIDER_REPO_URL',
  PROVIDER_GIT_CLONE_BYPASS = 'PROVIDER_GIT_CLONE_BYPASS',

  AGENT_PATH = 'AGENT_PATH',
  AGENT_BUILD_BYPASS = 'AGENT_BUILD_BYPASS',
  AGENT_PROJECT_TARGET = 'AGENT_PROJECT_TARGET',
  AGENT_REBUILD = 'AGENT_REBUILD',
  AGENT_VERBOSITY = 'AGENT_VERBOSITY',
}

export default envEnum;
