enum envEnum {
  PROVIDER = 'PROVIDER',
  PROVIDER_OWNER = 'PROVIDER_OWNER',
  PROVIDER_TOKEN = 'PROVIDER_TOKEN',
  PROVIDER_REPO = 'PROVIDER_REPO',
  PROVIDER_PR_NUMBER = 'PROVIDER_PR_NUMBER',
  // PROVIDER_URL = 'PROVIDER_URL',
  // PROVIDER_API_URL = 'PROVIDER_API_URL',

  AGENT_PATH = 'AGENT_PATH',
  AGENT_PROJECT_TARGET = 'AGENT_PROJECT_TARGET',
  AGENT_REBUILD = 'AGENT_REBUILD',
  AGENT_VERBOSITY = 'AGENT_VERBOSITY',
  AGENT_ERROR_LOG_PATH = 'AGENT_ERROR_LOG_PATH',
  AGENT_WARN_LOG_PATH = 'AGENT_WARN_LOG_PATH',
  AGENT_LOG_PATH = 'AGENT_LOG_PATH',
}

export default envEnum;
