name: Release

on:
  release:
    types: [ created ]

jobs:
  build:
    env:
      VERSION: ${{ github.event.release.tag_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Version ${{ env.VERSION }} validity check
        run: |
          if [ $(npm info codecoach@^${{ env.VERSION }} | wc -c) -gt 0 ]; then
            echo "Release version must be greater than existing released versions."
            exit 1
          fi

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          always-auth: true
          registry-url: https://registry.npmjs.org/

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - name: Install dependencies
        run: yarn

      - name: Publish version ${{ env.VERSION }}
        run: yarn publish --access public --new-version ${{ env.VERSION }} --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
