repo:
  url: https://gitlab.com/codeleague/codecoach
  pr: 40
  token: 123qwe123qwe123qwe123
  gitlabProjectId: "12"
buildLogFiles:
  - type: tslint
    path: /path/to/log.json
    cwd: /repo/src
output: ./output.json
